### ISSUE TITLE
sos report template switch box conflicts with TOC side panel

### ISSUE THREAD

**Issue by gaow** [vatlab/jnbinder#3]
See this page for example:

http://stephenslab.github.io/gtex-eqtls/analysis/20170829_MASH_Paper.html

It uses the `sos-report` template. But the floating box to turn on/off the reports appear at the left corner of the TOC side panel and conflicts with it -- making the items it covers unclickable.

Is good idea to embed that floating box to the right side of the HTML page after `<body>`, making it visible at all times yet low profile?

**Comment by BoPeng** [comment]
Is the entire page generated from a template or the generated page is embedded as a frame?

**Comment by gaow** [comment]
The entire page is generated from a template -- I merged your sos-report with the default jnbinder template. 

I find even a much plain version works better (more practical) for `jnbinder`:

![2017-08-29-21-04-21_scrot](https://user-images.githubusercontent.com/917985/29852091-b00731bc-8cfd-11e7-9499-754d367aaf88.png)

Do you have some quick suggestions that I can do to improve?

**Comment by BoPeng** [comment]
For this particular page with lots of other navigation links, there is no need to hide the control panel. I am not sure what is the best place for these buttons though.

**Comment by gaow** [comment]
Ok in that case let me place it like this for now for jnbinder + report template, until we find a better place for it
